layout : facebook
disqus :
  short_name :
livefyre :
  site_id : 
intensedebate :
  account : 
facebook : 216185801757014
  appid : http://hypermodern.ruhoh.com
  num_posts: 5
  width: 580
  colorscheme: light
