layout : facebook
disqus :
  short_name : jekyllbootstrap
livefyre :
  site_id : 123
intensedebate :
  account : 123abc
facebook :
  appid : 216185801757014
  num_posts: 5
  width: 580
  colorscheme: light
