title : ALLRISK.ORG
tagline: Take the question marks in your life and change them into exclamation points
author :
  name : Pete Ippel
  email : pete@allrisk.org
  github : hypermodern
  twitter : hypermodern
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
